# Este modelo do AWS SAM foi gerado a partir da configuração da sua função. Se sua
# função tiver um ou mais acionadores, observe que os recursos da AWS associados a
# esses acionadores não estão totalmente especificados nesse modelo e incluem
# valores de espaço reservado. Abra esse modelo no AWS Application Composer ou em
# seu IDE favorito e modifique-o para especificar uma aplicação com tecnologia sem
# servidor com outros recursos da AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  apisobreviventes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: 021891584200.dkr.ecr.us-east-1.amazonaws.com/case_itau:v10
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /sobreviventes
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /sobreviventes
            Method: POST
        Api3:
          Type: Api
          Properties:
            Path: /sobreviventes
            Method: DELETE
